package org.fluffy.pet.rms.resourcemanagement.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.fluffy.pet.rms.resourcemanagement.enums.Status;
import org.fluffy.pet.rms.resourcemanagement.util.DynamoConstants;

import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@SuperBuilder
@EqualsAndHashCode
@DynamoDBDocument
public class BaseEntity {
    @DynamoDBHashKey(attributeName = DynamoConstants.ID)
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = DynamoConstants.STATUS)
    private Status status;

    @DynamoDBVersionAttribute
    @DynamoDBAttribute(attributeName = DynamoConstants.VERSION)
    private Long version;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBAttribute(attributeName = DynamoConstants.CREATED_AT)
    private Date createdAt;

    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    @DynamoDBAttribute(attributeName = DynamoConstants.UPDATED_AT)
    private Date updatedAt;

    @DynamoDBAttribute(attributeName = DynamoConstants.CREATED_BY)
    private String createdBy;

    @DynamoDBAttribute(attributeName = DynamoConstants.UPDATED_BY)
    private String updatedBy;
}
