apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-pet
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fluffy-pet
  template:
    metadata:
      labels:
        app: fluffy-pet
    spec:
      containers:
      - name: fluffy-pet
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: AWS_ACCESS_KEY_ID
          value: AKIATCKAQMYEYF6OEWN2
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        - name: MONGO_DB_URL
          value: mongodb://fluffyPet:fluffyPetRoot@fluffy-pet-211125560841.us-east-1.docdb-elastic.amazonaws.com:27017/resource-management
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1