apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-pet
  namespace: fluffy-pet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluffy-pet
  template:
    metadata:
      labels:
        app: fluffy-pet
    spec:
      containers:
      - name: fluffy-pet
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: mongo-root-password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mongo-app-secret
              key: aws-secret-key-id
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1