apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-pet
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fluffy-pet
  template:
    metadata:
      labels:
        app: fluffy-pet
    spec:
      containers:
      - name: fluffy-pet
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: SPRING_PROFILES_ACTIVE_VALUE
        - name: AWS_ACCESS_KEY_ID
          value: AWS_ACCESS_KEY_ID_VALUE
        - name: AWS_SECRET_ACCESS_KEY
          value: AWS_SECRET_ACCESS_KEY_VALUE
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1