apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-pet
  namespace: fluffy-pet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fluffy-pet
  template:
    metadata:
      labels:
        app: fluffy-pet
    spec:
      containers:
      - name: fluffy-pet
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1