apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluffy-pet
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fluffy-pet
  template:
    metadata:
      labels:
        app: fluffy-pet
    spec:
      containers:
      - name: fluffy-pet
        image: 211125560841.dkr.ecr.us-east-1.amazonaws.com/fluffy_pet_resource_management_system:1d3189e8bd94ab504006a45af2725af5faaf9a8a
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: AWS_ACCESS_KEY_ID
          value: AKIATCKAQMYEYF6OEWN2
        - name: AWS_SECRET_ACCESS_KEY
          value: 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

