apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  mongo-root-username: Zmx1ZmZ5LXBldC1tb25nby1kYi11c2VybmFtZQ==
  mongo-root-password: Zmx1ZmZ5LXBldC1tb25nby1kYi1wYXNzd29yZA==