apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: mongo
spec:
  type: NodePort
  ports:
    - port: 7070
      nodePort: 32000
      targetPort: 7070
  selector:
    app: mongo-express