apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongo
type: Opaque
data:
  mongo-root-username: <base64-encoded-root-username>
  mongo-root-password: <base64-encoded-root-password>