apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-final-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-0f250739259379ef5
    fsType: ext4
