apiVersion: v1
kind: Service
metadata:
  name: fluffy-pet
  namespace: default
spec:
  selector:
    app: fluffy-pet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
