apiVersion: v1
kind: Service
metadata:
  name: fluffy-pet
  namespace: fluffy-pet
spec:
  selector:
    app: fluffy-pet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
