name: Deploy to EKS

on:
  workflow_dispatch:
    inputs:
      refresh_mongo:
        description: 'Refresh MongoDB volume and deployment'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Fetch GitHub Actions IP addresses
        id: get_github_ips
        run: |
          curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/meta | jq -r '.actions[]' > github_ips.txt

      - name: Allow Inbound Traffic from GitHub Actions IPs
        run: |
          REGION="ap-south-1"
          SECURITY_GROUP_ID="${{ secrets.SECURITY_GROUP }}"
          while read -r ip; do
            echo "IP Address = $ip"
            aws ec2 authorize-security-group-ingress --region $REGION --group-id $SECURITY_GROUP_ID --protocol tcp --port 443 --cidr "$ip"
          done < github_ips.txt

#      - name: Build, tag, and push image to Amazon ECR
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          ECR_REPOSITORY: fluffy_pet_resource_management_system
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name fluffy-pet --region ap-south-1

      - name: Verify kubeconfig
        run: |
          kubectl config view
          kubectl config current-context
          kubectl cluster-info

#      - name: Refresh MongoDB Volume
#        if: ${{ github.event.inputs.refresh_mongo == 'true' }}
#        run: |
#          kubectl delete pvc mongo-pvc --ignore-not-found
#          kubectl delete pv mongo-pv --ignore-not-found
#          kubectl apply -f deployment/persistent-volume.yaml
#          kubectl apply -f deployment/persistent-volume-claim.yaml

#      - name: Deploy MongoDB
#        if: ${{ github.event.inputs.refresh_mongo == 'true' }}
#        run: |
#          kubectl apply --validate=false -f deployment/mongodb-deployment.yaml
#          kubectl apply --validate=false -f deployment/mongodb-service.yaml

#      - name: Deploy Application
#        env:
#          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          ECR_REPOSITORY: fluffy_pet_resource_management_system
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" deployment/deployment.yaml && \
#          kubectl apply --validate=false -f deployment/deployment.yaml --v=8
#          kubectl apply --validate=false -f deployment/service.yaml --v=8